name: Gatsby Deploy

on:
  push:
    branches: gh-pages

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "example@example.example"
          git config --global user.name "example"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn
      - name: Deploy
        run: npm run deploy:ci